# Name(s)
**Sydney Baroya**

**Instructions:** This is an individual assignment, but you may discuss your code with your neighbors.

# Python and NumPy

While other IDEs exist for Python development and for data science related activities, one of the most popular environments is Jupyter Notebooks.

This lab is not intended to teach you everything you will use in this course. Instead, it is designed to give you exposure to some critical components from NumPy that we will rely upon routinely.

## Exercise 0
Please read and reference the following as your progress through this course. 

* [What is the Jupyter Notebook?](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/What%20is%20the%20Jupyter%20Notebook.ipynb#)
* [Notebook Tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)
* [Notebook Basics](https://nbviewer.jupyter.org/github/jupyter/notebook/blob/master/docs/source/examples/Notebook/Notebook%20Basics.ipynb)

**In the space provided below, what are three things that still remain unclear or need further explanation?**

**YOUR ANSWER HERE**

## Exercises 1-7
For the following exercises please read the Python appendix in the Marsland textbook and answer problems A.1-A.7 in the space provided below.

## Exercise 1

In [56]:
# YOUR SOLUTION HERE
a = []
for i in range(0,6):
    new = []
    for j in range(0,4):
        new.append(2)
    a.append(new)
a=np.asarray(a)
print(a) 

[[2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]
 [2 2 2 2]]


## Exercise 2

In [63]:
# YOUR SOLUTION HERE
import numpy as np
b = np.eye(6,4)
b=map(lambda x: np.asarray((x*2)+1), b)
b=np.asarray(list(b))
print(b)

[[3. 1. 1. 1.]
 [1. 3. 1. 1.]
 [1. 1. 3. 1.]
 [1. 1. 1. 3.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## Exercise 3

In [67]:
# YOUR SOLUTION HERE
m = a*b
print(m)
# d = np.dot(a,b)
# print(d)

[[6. 2. 2. 2.]
 [2. 6. 2. 2.]
 [2. 2. 6. 2.]
 [2. 2. 2. 6.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]


The dot product in the above problem does not work because the dimensions of the two matrices do not line up to perform a dot product on them.

## Exercise 4

In [71]:
# YOUR SOLUTION HERE
a_trans = np.dot(a.transpose(), b)
b_trans = np.dot(a, b.transpose())
print("a transposed dot product: ", a_trans)
print("a transposed size: ", np.size(a_trans))
print("b transposed dot product: ", b_trans)
print("b transposed size: ", np.size(b_trans))

a transposed dot product:  [[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
a transposed size:  16
b transposed dot product:  [[12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]
 [12. 12. 12. 12.  8.  8.]]
b transposed size:  36


The results are different sizes because...

## Exercise 5

In [ ]:
# YOUR SOLUTION HERE

## Exercise 6

In [ ]:
# YOUR SOLUTION HERE

## Exercise 7

In [ ]:
# YOUR SOLUTION HERE

## Excercises 8-???
While the Marsland book avoids using another popular package called Pandas, we will use it at times throughout this course. Please read and study [10 minutes to Pandas](https://pandas.pydata.org/pandas-docs/stable/getting_started/10min.html) before proceeding to any of the exercises below.

## Exercise 8
Repeat exercise A.1 from Marsland, but create a Pandas DataFrame instead of a NumPy array.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 9
Repeat exercise A.2 using a DataFrame instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 10
Repeat exercise A.3 using DataFrames instead.

In [ ]:
# YOUR SOLUTION HERE

## Exercise 11
Repeat exercise A.7 using a dataframe.

In [ ]:
# YOUR SOLUTION HERE

## Exercises 12-14
Now let's look at a real dataset, and talk about ``.loc``. For this exercise, we will use the popular Titanic dataset from Kaggle. Here is some sample code to read it into a dataframe.

In [ ]:
titanic_df = pd.read_csv(
    "https://raw.githubusercontent.com/dlsun/data-science-book/master/data/titanic.csv"
)
titanic_df

Notice how we have nice headers and mixed datatypes? That is one of the reasons we might use Pandas. Please refresh your memory by looking at the 10 minutes to Pandas again, but then answer the following.

## Exercise 12
How do you select the ``name`` column without using .iloc?

In [ ]:
## YOUR SOLUTION HERE

## Exercise 13
After setting the index to ``sex``, how do you select all passengers that are ``female``? And how many female passengers are there?

In [ ]:
## YOUR SOLUTION HERE
titanic_df.set_index('sex',inplace=True)

## Exercise 14
How do you reset the index?

In [ ]:
## YOUR SOLUTION HERE